### ISSUE TITLE
Can't build FTSPlot on Ubuntu 16.04

### ISSUE THREAD

**Issue by galenlynch** [MichaelRiss/FTSPlot#3]
I cannot build FTSPlot using the instructions in your README on Ubuntu 16.04. A number of build targets fail for me with with a linker error similar to this:  

```
/usr/bin/ld: CMakeFiles/FTSPlot.dir/FTSPlotMain.cpp.o: undefined reference to symbol 'XInitThreads'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/FTSPlot.dir/build.make:165: recipe for target 'FTSPlot' failed
make[2]: *** [FTSPlot] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/FTSPlot.dir/all' failed
make[1]: *** [CMakeFiles/FTSPlot.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

If I manually edit the link.txt files to include `-lX11` then FTSPlot builds correctly. 

I'm not familiar enough with CMake or Qt to fix this in the `CMakeLists.txt` file itself.

**Comment by MichaelRiss** [comment]
Thanks for bringing this up. I will look into this as soon as possible.

**Comment by XavierTolza** [comment]
Any news on this issue? Still having the same on Ubuntu 18.04.
Sharing my workaround: you can compile with the following script:
```
mkdir build
cd build
sudo apt install libx11-dev
cmake ..
sed -i 's/-lGLU/-lGLU -lX11/g' ./CMakeFiles/FTSPlot.dir/link.txt
sed -i 's/-lQtGui/-lQtGui -lX11/g' ./tests/CMakeFiles/runTests.dir/link.txt
sed -i 's/-lGLU/-lGLU -lX11/g' ./benchmarks/CMakeFiles/FTSPlotBench.dir/link.txt
make
```

**Comment by MichaelRiss** [comment]
Sorry guys, I didn't have a lot of time the last years. But now I finally got to it. Thanks for the input!
